### PR TITLE
Straight like me

### PR DESCRIPTION
**Pull request by master7720**

### CODE REVIEW

**Comment by TwoThreeTwo** [comment]
Creating a PR just to press tabs on a few lines?? Stop making pull requests that don't help the actual dev lmfao

**Comment by master7720** [comment]
> Creating a PR just to press tabs on a few lines?? Stop making pull requests that don't help the actual dev lmfao

no

**Comment by master7720** [comment]
i do this cuz ppl look at it and they seem to be mad or smt and its funny

**Comment by HausemasterIssue** [comment]
Master7720 is an amazing coder wym @TwoThreeTwo? His contributions are always welcome, and they should be in this repository. It's open source so don't complain people wanna contribute.

**Comment by master7720** [comment]
!!!!! same gos for you @HausemasterIssue spidersense is FULLY custom

**Pull request closed without merging**
